import Head from "next/head";
import Header from "./Header";

interface Props {
  children: React.ReactElement | React.ReactElement[]
}

const BaseLayout = ({children}: Props) => {
  return (
    <>
      <Head>
        <title>Cozinhando</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main className="flex min-h-screen flex-col items-center">
        <Header />
        {children}
      </main>
    </>
  );
};

export default BaseLayout;
