import Head from "next/head";
import Header from "./Header";
import CreateProfile from "./CreateProfile";
import { useState } from "react";

interface Props {
  children: React.ReactElement | React.ReactElement[];
}

const BaseLayout = ({ children }: Props) => {
  const [createProfile, setCreateProfile] = useState<boolean>(false);

  return (
    <>
      <Head>
        <title>Cozinhando</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header setCreateProfile={() => setCreateProfile(true)} />
      <main className="max-h-screen">
        {createProfile && (
          <CreateProfile setCreateProfile={() => setCreateProfile(false)} />
        )}
        {children}
      </main>
    </>
  );
};

export default BaseLayout;
